### ISSUE TITLE
Global header title

### ISSUE THREAD

**Issue by charlesjdillon** [washingtonstateuniversity/pharmacy.wsu.edu#3]
@philcable I can not change the global header title to College of Pharmacy in the customizer. It is keeping it the page title.

**Comment by philcable** [comment]
@charlesjdillon The header element that displays the site title has been hidden with CSS - https://github.com/washingtonstateuniversity/pharmacy.wsu.edu/blob/master/css/01-header.css#L14.

**Comment by philcable** [comment]
This is due to the `Spine Main Header` > `Top Header Text` meta field being used on some pages. We want to preserve that functionality as the override may be intentional in some cases, so I'm closing this out.
